// POR EJEMPLO EN ESTE MOMENTO APARECE ERROR YA QUE NO SE HA DEFINIDO LA VARIABLE productPrice Y productName
// EN OTRO ARCHIVO Y POR ENDE NO SE PUEDE USAR EN ESTE ARCHIVO PERO PARA RESOLVERLO LO QUE SE HACE ES CREAR UNA FUNCION
// ANONUMA AUTOEJECUTABLE QUE SE PUEDE VER EN EL ARCHIVO 3-typing.ts

let productName = "Calofe";
let productPrice = 20;
